blank_issues_enabled: false
contact_links:
  - name: adasApps AppExchange Listing
    url: https://appexchange.salesforce.com
    about: Visit our AppExchange listing for demos and general information
